### ISSUE TITLE
Problems seeing in the API monitor 

### ISSUE THREAD

**Issue by Ataos** [Apress/practical-video-game-bots#1]
Some functions is not showing for me in API Monitor.
I tried to run script like PixelSearch and I dont get any return of API Monitor for doing that like I see in the photos. This is a very good book and I'm enjoying a lot reading and learning with it but I would like to know why it's diferent the same thing that I tried to do. (In API filter only User Interaction/Keyboard and mouse input is enabled, I dont know if it is something with that)

![image](https://user-images.githubusercontent.com/36573176/67613919-e240f980-f789-11e9-9c51-9908df5a70bb.png)
![image](https://user-images.githubusercontent.com/36573176/67613923-ee2cbb80-f789-11e9-8512-9f8dc7ccdb3b.png)

**Comment by ellysh** [comment]
Hello Ataos,

Thank you for your message! You asked a good question. 

The "StretchBlt" function call, which we are looking for, is implemented in the "gdi32.dll" system library. This library is not covered by the "User Interaction/Keyboard and Mouse Input" filters of API Monitor. These filters were actual for the previous section of the book ("OS-Level Data Embedding"). There we have considered system libraries, which are responsible for the processing user input. Now we consider system libraries for manipulating graphical objects and output information on the screen.

Can you please repeat your test with the "Graphics and Gaming" filters enabled? Then you can search for the text "StretchBlt (" and quickly find the necessary calls.

Please, have a look at the attached screenshot.

![api-monitor](https://user-images.githubusercontent.com/1086198/67618357-a5f3b480-f7ee-11e9-8c40-f6941f976eaa.png)

**Comment by Ataos** [comment]
After you explained it to me it was easy to understand. Thank you very much

![image](https://user-images.githubusercontent.com/36573176/67629402-d6ba0500-f853-11e9-83ba-fa9915ad9253.png)
